services:
  - type: web
    name: indicadores-motoristas
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: "postgres://usuario:senha@host:porta/banco"
      - key: SECRET_KEY
        value: "uma-chave-secreta-aqui"
